### ISSUE TITLE
IsSimilar Method Only Uses Primary Value

### ISSUE THREAD

**Issue by m1nkeh** [eldersantos/phonix#6]
No sure if this is an issue or not, but looking at the code, is the IsSimilar method only using the 0 location on the array, aka the primary Double Metaphone value?

Should it not be something like....

- (Primary Key = Primary Key) = **Strongest Match**
- (Secondary Key = Primary Key) = **Normal Match**
- (Primary Key = Secondary Key) = **Normal Match**
- (Alternate Key = Alternate Key) = **Minimal Match**

Happy to implement, and issue a PR, but.. thoughts?

**Comment by eldersantos** [comment]
hey @m1nkeh it was implemented following the original article http://www.drdobbs.com/the-double-metaphone-search-algorithm/184401251?pgno=2, but I can review it for sure

**Comment by hay12396** [comment]
Hey, Anything on this yet? :)

**Comment by m1nkeh** [comment]
soz, forgot to reply.. @eldersantos i read that post, but am not sure that is has the detail necessary in order to know that it was correctly implemented... to be honest, i am sure it's fine in "real world" usage. But when comparing the results from phonix to that of other implementations of double metaphone, such as in R, we were seeing differences.. if you like, i can dig them up?

**Comment by eldersantos** [comment]
Hi Chris, yeah feel free to send a PR

cheers

**Comment by eldersantos** [comment]
Closed with the PR https://github.com/eldersantos/phonix/pull/8#issue-224246276
