### ISSUE TITLE
Not able to execute the program

### ISSUE THREAD

**Issue by noufanpmc** [eldersantos/phonix#7]
I've downloaded the zip file  and opened as a project in Visual Studio 2017, When I clicked F5 to run the program its showing error:
program does not contain static 'main' method suitable for an entry point

Can you please solve this problem and help me to learn the working of the phonetics algorithm that you have built.

Thanks in advance :)

**Comment by eldersantos** [comment]
hey @noufanpmc this is a library project (or dll) you need to use it from another project.
Basically, from your .exe or webproject you add a reference to Phonix and then instantiate a class.
The easiest way to add the reference is by using nuget [https://www.nuget.org/packages/Phonix/](url)

Hope you get luck

**Comment by noufanpmc** [comment]
Ohh okay, 
Thank you so much for the reply.
So can you suggest some links to learn how to use this phonix library in other projects.
It'll be a great help for me to know how it works and all.
