### ISSUE TITLE
Although targeted for .Net Standard 2.0 phonix is loaded by full framework

### ISSUE THREAD

**Issue by AlbertoBN** [eldersantos/phonix#9]
[warn]: OmniSharp.MSBuild.ProjectLoader
        Package 'Phonix 1.0.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by eldersantos** [comment]
Hi @AlbertoBN , not sure if I understand the issue you reported. Phonix was tested with pure .net core project and it is not loading framework 4.6.1. If you want to check the source code, please make sure you are using the solution named "Solution_VSCore"

**Comment by lubiepomaranczki** [comment]
Hi @eldersantos,
I think I know what @AlbertoBN is talking about. When adding Phonix to the project you can see the warning 
![this warning](https://i.imgur.com/V4j6Sbm.png)
It looks like the project is targeting .NET Standard 2.0. Can you please check if your nuget package is targeting the same? Or is there any chance you didn't create a package after migrating to .NET Standard 2.0?

**Comment by lubiepomaranczki** [comment]
Hi @eldersantos 👋
As you can see above I've created a PR with a possible fix. I will be much obliged if you can please take a look. 

Thanks for your work! 🙌

**Comment by codingbadger** [comment]
Hi @eldersantos 

Any chance this PR could be merged in?

**Comment by kawazoe** [comment]
@lubiepomaranczki I just took a look at the package and I don't think your PR will fix the problem. A project targeting netStandard2.0 or 2.1 shouldn't have any problem loading a library targeting even netStandard1.0.

The real problem comes from the NuGet package only including the net40 build. No update has been published since 2014 on this package and netStandard support was added in 2018.

@eldersantos Do you think you could publish an update of the package?

**Comment by eldersantos** [comment]
@kawazoe I will take a look into this over the weekend, not sure too if the PR will work, so I need to test it

**Comment by eldersantos** [comment]
Did a push for a possible fix, v1.0.2 is already in Nuget, let me know any problems.

**Comment by kawazoe** [comment]
It looks good. The package now reference the netstandard2.0 lib. Though, you lost your package description in the update so you might want to fix that for SEO.

**Comment by eldersantos** [comment]
Yeah, I will fix that later, Nuget + VS + Nuget spec is not talking very well with each other ;(
